timestamp: '2025-11-29T20:32:08.319052'
joints:
  shoulder_pan:
    min:
      ticks: 3439
      speed: 0
      load: 0
    center:
      ticks: 1929
      speed: 0
      load: 0
    max:
      ticks: 433
      speed: 0
      load: 0
  shoulder_lift:
    min:
      ticks: 3912
      speed: 0
      load: 0
    center:
      ticks: 2038
      speed: 0
      load: 0
    max:
      ticks: 2109
      speed: -1
      load: 0
  elbow_flex:
    min:
      ticks: 2072
      speed: 0
      load: 0
    center:
      ticks: 2009
      speed: -1
      load: 0
    max:
      ticks: 160
      speed: -50
      load: 0
  wrist_flex:
    min:
      ticks: 1919
      speed: 0
      load: 0
    center:
      ticks: 2022
      speed: 0
      load: 0
    max:
      ticks: 99
      speed: 0
      load: 0
  wrist_roll:
    min:
      ticks: 2256
      speed: 0
      load: 0
    center:
      ticks: 2068
      speed: 0
      load: 0
    max:
      ticks: 1933
      speed: 0
      load: 0
  gripper:
    min:
      ticks: 213
      speed: 0
      load: 0
    center:
      ticks: 2116
      speed: 50
      load: 0
    max:
      ticks: 2880
      speed: 3577
      load: 0
